c_compiler:
- gcc
c_compiler_version:
- '12'
cdt_name:
- cos7
cdt_arch:
- armv7l
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
elfutils:
- '0.191'
lz4_c:
- 1.9.3
openssl:
- '3'
p11_kit:
- '0.24'
target_platform:
- linux-armv7l
xz:
- '5'
zstd:
- '1.5'
